#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Xama.JTPorts.MaterialTextField.Resource", IsApplication=false)]

namespace Xama.JTPorts.MaterialTextField
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public static int mtf_animationDuration = 2130771972;
			
			// aapt resource value: 0x7f010006
			public static int mtf_backgroundColor = 2130771974;
			
			// aapt resource value: 0x7f010000
			public static int mtf_cardCollapsedHeight = 2130771968;
			
			// aapt resource value: 0x7f010003
			public static int mtf_hasFocus = 2130771971;
			
			// aapt resource value: 0x7f010002
			public static int mtf_image = 2130771970;
			
			// aapt resource value: 0x7f010001
			public static int mtf_labelColor = 2130771969;
			
			// aapt resource value: 0x7f010005
			public static int mtf_openKeyboardOnFocus = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040001
			public static int mtf_cardHeight_final = 2130968577;
			
			// aapt resource value: 0x7f040000
			public static int mtf_cardHeight_initial = 2130968576;
			
			// aapt resource value: 0x7f040002
			public static int mtf_corner_radius = 2130968578;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int card = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public static int mtf_card = 2131099649;
			
			// aapt resource value: 0x7f060003
			public static int mtf_editTextLayout = 2131099651;
			
			// aapt resource value: 0x7f060002
			public static int mtf_image = 2131099650;
			
			// aapt resource value: 0x7f060000
			public static int mtf_label = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int mtf_layout = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public static int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public static int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MaterialTextField = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: 4
			public static int MaterialTextField_mtf_animationDuration = 4;
			
			// aapt resource value: 6
			public static int MaterialTextField_mtf_backgroundColor = 6;
			
			// aapt resource value: 0
			public static int MaterialTextField_mtf_cardCollapsedHeight = 0;
			
			// aapt resource value: 3
			public static int MaterialTextField_mtf_hasFocus = 3;
			
			// aapt resource value: 2
			public static int MaterialTextField_mtf_image = 2;
			
			// aapt resource value: 1
			public static int MaterialTextField_mtf_labelColor = 1;
			
			// aapt resource value: 5
			public static int MaterialTextField_mtf_openKeyboardOnFocus = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
